env:
    #global environmental variables control magento instal parameters
    #see also hosts in addons.
    global:
    - MAGE2_FAKE_URL=http://magento-2-travis.dev
    - MAGE2_ADMIN_EMAIL=samet.yilmaz@example.com
    - MAGE2_ADMIN_FIRST_NAME=Samet
    - MAGE2_ADMIN_LAST_NAME=Yilmaz
    - MAGE2_ADMIN_USERNAME=admin            
    - MAGE2_ADMIN_PASSWORD=ih3artmagento            
    - MAGE2_ADMIN_DBNAME=magento_2_travis
    - MAGE2_DB_HOST=127.0.0.1
    - MAGE2_DB_USER=root
    - MAGE2_DB_PASS=
    - MAGE2_DB_NAME=magento_2_travis
    - REPOSITORY_TO_TEST=https://github.com/syilmaz/magmi-git.git
    - BRANCH_TO_TEST=magento2-tests
addons:
  hosts:
    # should match MAGE2_FAKE_URL above
    - magento-2-travis.dev    
language: php
sudo: required
dist: trusty
cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.nvm
    - $HOME/node_modules
    - $HOME/yarn.lock
php:
   - 5.6
#   - 7.0
before_script:
    # some useful debugging stuff for travis
    #- curl http://magento-2-travis.dev/index.php
    #- curl http://magento-2-travis.dev/  
    #- sudo find /var/log/apache2 -exec cat '{}' \;      
    #- sudo cat /etc/apache2/sites-available/000-default.conf
    #- sudo cat /etc/apache2/sites-enabled/000-default.conf    
    #- sudo apachectl -V
    #- sudo apache2ctl -V
    #- ls -lh $TRAVIS_BUILD_DIR
    #- sudo ls /etc/apache2/sites-available
    #- sudo ls /etc/apache2/sites-enabled
    #- pwd    
    #    
    # get latest composer 
    - composer selfupdate
    - if [ -n "$GITHUB_ACCESS_TOKEN" ]; then composer config github-oauth.github.com ${GITHUB_ACCESS_TOKEN}; fi;
    # disable xdebug for perf    
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini   
    # add multiverse support to get MySQL 5.6 update apt
    - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty multiverse" && sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty-updates multiverse"
    - sudo apt-get update -qq 
    # add mysql 5.6
    - sudo apt-get remove -y -qq --purge mysql-common mysql-server-5.5 mysql-server-core-5.5 mysql-client-5.5 mysql-client-core-5.5
    - sudo apt-get -y -qq autoremove;
    - sudo apt-get -y -qq autoclean;
    - sudo apt-get install -y -qq mysql-server-5.6 mysql-client-5.6;    
    - mysql -uroot -e 'SET @@global.sql_mode = NO_ENGINE_SUBSTITUTION; CREATE DATABASE magento_2_travis;';
    # add apache
    - sudo apt-get install -y -qq apache2 libapache2-mod-fastcgi
    #   enable php-fpm -- www.conf.default is PHP 7 only, so we dev/null any copy problems    
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf 2>/dev/null || true  
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
    - sudo a2enmod rewrite actions fastcgi alias
    - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
    #   awful hack used during travis debugging that I swear I'm going to remove
    #   but then again you're reading this so I didn't remove it and **sigh**    
    - sudo chmod 777 /home /home/travis /home/travis/build            

    #   configure apache virtual hosts, assumes 000-default.conf is there
    - sudo cp -f .travis/travis-ci-apache /etc/apache2/sites-available/000-default.conf
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
    # restart apache
    - sudo service apache2 restart 

    # clone main magento github repository
    - git clone --depth=1 https://github.com/magento/magento2
    # install Magento
    - cd magento2  
    # switch to specific branch in you like
    #- git checkout 2.0;git checkout tags/2.0.2
    # run installation command using evn variables set above
    - composer install
    - php bin/magento setup:install --admin-email "$MAGE2_ADMIN_EMAIL" --admin-firstname "$MAGE2_ADMIN_FIRST_NAME" --admin-lastname "$MAGE2_ADMIN_LAST_NAME" --admin-password "$MAGE2_ADMIN_PASSWORD" --admin-user "$MAGE2_ADMIN_USERNAME" --backend-frontname admin --base-url "$MAGE2_FAKE_URL" --db-host $MAGE2_DB_HOST --db-name $MAGE2_DB_NAME --db-user $MAGE2_DB_USER --session-save files --use-rewrites 1 --use-secure 0 -vvv

    # clone the repo that should be tested
    - git clone "$REPOSITORY_TO_TEST" pub/magmi
    - cd pub/magmi
    - git checkout "$BRANCH_TO_TEST"
    - composer install
    - cd magmi

    # test that magento is installed
    - curl "$MAGE2_FAKE_URL/index.php" > /tmp/output.txt
    - test 'grep -Fx "magento-2-travis.dev" /tmp/output.txt'

script:
  - phpunit -c tests/unit/phpunit.xml --testsuite unit
  - phpunit -c tests/integration/phpunit.xml --testsuite integration